<?php

use \Cake\Core\Configure;

Configure::write('permissions', [
    'Categories'     => [
        'index'          => 100,
        'view'           => 101,
        'add'            => 102,
        'edit'           => 103,
        'delete'         => 104,
        'deleteSelected' => 105,
    ],
    'Countries'      => [
        'index'          => 200,
        'view'           => 201,
        'add'            => 202,
        'edit'           => 203,
        'delete'         => 204,
        'deleteSelected' => 205,
    ],
    'Hotels'         => [
        'index'          => 300,
        'view'           => 301,
        'add'            => 302,
        'edit'           => 303,
        'delete'         => 304,
        'deleteSelected' => 305,
    ],
    'MailTemplates'  => [
        'index'          => 400,
        'view'           => 401,
        'add'            => 402,
        'edit'           => 403,
        'deleteSelected' => 405,
    ],
    'Menus'          => [
        'index'          => 500,
        'add'            => 501,
        'edit'           => 502,
        'deleteSelected' => 505,
    ],
    'NewCategories'  => [
        'index'          => 600,
        'view'           => 601,
        'add'            => 602,
        'edit'           => 603,
        'delete'         => 604,
        'deleteSelected' => 605,
    ],
    'News'           => [
        'index'          => 700,
        'view'           => 701,
        'add'            => 702,
        'edit'           => 703,
        'delete'         => 704,
        'deleteSelected' => 705,
    ],
    'Orders'         => [
        'index'          => 800,
        'view'           => 801,
        'add'            => 802,
        'edit'           => 803,
        'delete'         => 804,
        'deleteSelected' => 805,
        'invoice'        => 806,
        'invoicePrint'   => 807,
    ],
    'OurServices'    => [
        'index'          => 900,
        'view'           => 901,
        'add'            => 902,
        'edit'           => 903,
        'delete'         => 904,
        'deleteSelected' => 905,
    ],
    'Pages'          => [
        'index'          => 1000,
        'view'           => 1001,
        'add'            => 1002,
        'edit'           => 1003,
        'delete'         => 1004,
        'deleteSelected' => 1005,
    ],
    'PaymentMethods' => [
        'index'          => 1100,
        'view'           => 1101,
        'add'            => 1102,
        'edit'           => 1103,
        'delete'         => 1104,
        'deleteSelected' => 1105,
    ],
    'Products'       => [
        'index'          => 1200,
        'view'           => 1201,
        'add'            => 1202,
        'edit'           => 1203,
        'delete'         => 1204,
        'deleteSelected' => 1205,
        'updateAll'      => 1206,
    ],
    'Services'       => [
        'index'          => 1300,
        'view'           => 1301,
        'add'            => 1302,
        'edit'           => 1303,
        'delete'         => 1304,
        'deleteSelected' => 1305,
    ],
    'Settings'       => [
        'update' => 1400,
    ],
    'Shippers'       => [
        'index'          => 1500,
        'view'           => 1501,
        'add'            => 1502,
        'edit'           => 1503,
        'delete'         => 1504,
        'deleteSelected' => 1505,
    ],
    'ShippingZones'  => [
        'index'          => 1600,
        'view'           => 1601,
        'add'            => 1602,
        'edit'           => 1603,
        'delete'         => 1604,
        'deleteSelected' => 1605,
    ],
    'Sliders'        => [
        'index'          => 1700,
        'view'           => 1701,
        'add'            => 1702,
        'edit'           => 1703,
        'delete'         => 1704,
        'deleteSelected' => 1705,
    ],
    'Stores'         => [
        'index'          => 1800,
        'view'           => 1801,
        'add'            => 1802,
        'edit'           => 1803,
        'delete'         => 1804,
        'deleteSelected' => 1805,
    ],
    'Supports'       => [
        'index'          => 1900,
        'view'           => 1901,
        'add'            => 1902,
        'edit'           => 1903,
        'delete'         => 1904,
        'deleteSelected' => 1905,
    ],
    'Users'          => [
        'index'          => 2000,
        'view'           => 2001,
        'add'            => 2002,
        'edit'           => 2003,
        'delete'         => 2004,
        'deleteSelected' => 2005,
    ],
    'UserGroups'     => [
        'index'          => 2100,
        'view'           => 2101,
        'add'            => 2102,
        'edit'           => 2103,
        'delete'         => 2104,
        'deleteSelected' => 2105,
    ],
    'Dashboards'     => [
        'report'      => 2200,
        'customer'    => 2201,
        'profit'      => 2202,
        'reportOrder' => 2203,
    ],
    'OrderHistories' => [
        'index' => 2300,
    ],
]);
